# https://taskfile.dev

version: '3'

silent: true

tasks:
  world:
    desc: run all validation and pre-commit steps
    cmds:
      - task: start-dependencies
      - task: format
      - task: test
      - task: cleanup
      - task: stop-dependencies

  start-dependencies:
    desc: start development dependencies
    cmds: [ task: start-database, task: wait-for-database-ready ]

  start-database:
    dir: build/
    cmds: [ docker-compose up -d --force-recreate --remove-orphans --renew-anon-volumes ]

  wait-for-database-ready:
    # swallo error output as go mysql driver always prints to stderr
    cmds: [ go run tools/wait_for_database_ready.go 2> /dev/null ]

  format:
    desc: format sources
    cmds: [ go fmt ./... ]

  test:
    desc: run tests
    cmds: [ go test ./... ]

  cleanup:
    desc: cleanup go modules
    cmds: [ go mod verify, go mod tidy ]

  stop-dependencies:
    desc: start development dependencies
    dir: build/
    cmds: [ docker-compose down -v --remove-orphans  ]


  default:
    cmds: [ task: world ]