name: run tests
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install task
        run: brew install go-task/tap/go-task
        env:
          NOHOMEBREW_NO_AUTO_UPDATE: 1
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/checkout@v3
      - run: task world